### ISSUE TITLE
Add support for event attributes

### ISSUE THREAD

**Issue by janlisse** [benmur/riemann-scala-client#16]
Currently there is no way to send event attribute values (key-value pairs) to Riemann.
Would be nice to have this (The java Proto.Event#Builder already contains setAttributes methods ). 
I can create a PR to add support for this if you like.

**Comment by benmur** [comment]
Merged #17, thanks!

**Comment by janlisse** [comment]
You are welcome! Would you mind bumping a new minor release?

**Comment by benmur** [comment]
@janlisse I just released 0.4.0 since it was pending, it should be propagated shortly.
